<?php

return [
    'types' => [
        'cafe' => [
            'label' => 'Cafe / Coffee Shop',
            'categories' => ['Coffee', 'Tea', 'Pastries', 'Sandwiches'],
            'default_tax' => 10,
            'measurement_units' => ['cup', 'oz', 'ml'],
            'pos_layout' => 'grid',
            'table_management' => true,
        ],
        'retail' => [
            'label' => 'Retail / Shop',
            'categories' => ['General', 'Clothing', 'Grocery', 'Household'],
            'default_tax' => 15,
            'measurement_units' => ['pcs', 'kg', 'box'],
            'pos_layout' => 'grid',
            'table_management' => false,
        ],
        'supermarket' => [
            'label' => 'Supermarket / Grocery',
            'categories' => ['Dairy', 'Bakery', 'Meat', 'Produce', 'Beverages', 'Snacks'],
            'default_tax' => 8,
            'measurement_units' => ['pcs', 'kg', 'g', 'l', 'ml', 'box'],
            'pos_layout' => 'list',
            'table_management' => false,
        ],
        'restaurant' => [
            'label' => 'Restaurant',
            'categories' => ['Appetizers', 'Main Course', 'Desserts', 'Beverages', 'Sides'],
            'default_tax' => 12,
            'measurement_units' => ['serving', 'plate', 'bowl'],
            'pos_layout' => 'grid',
            'table_management' => true,
        ],
    ],
    'other_types' => [
        'Bakery' => 'Bakery',
        'Pharmacy' => 'Pharmacy',
        'Boutique' => 'Clothing Boutique',
        'Electronics' => 'Electronics Store',
        'Bookstore' => 'Bookstore',
        'Hardware' => 'Hardware Store',
    ],
    'currencies' => [
        'USD' => 'USD - US Dollar',
        'EUR' => 'EUR - Euro',
        'GBP' => 'GBP - British Pound',
        'JPY' => 'JPY - Japanese Yen',
        'CNY' => 'CNY - Chinese Yuan',
        'AUD' => 'AUD - Australian Dollar',
        'CAD' => 'CAD - Canadian Dollar',
        'CHF' => 'CHF - Swiss Franc',
        'HKD' => 'HKD - Hong Kong Dollar',
        'SGD' => 'SGD - Singapore Dollar',
        'SEK' => 'SEK - Swedish Krona',
        'KRW' => 'KRW - South Korean Won',
        'NOK' => 'NOK - Norwegian Krone',
        'NZD' => 'NZD - New Zealand Dollar',
        'INR' => 'INR - Indian Rupee',
        'MXN' => 'MXN - Mexican Peso',
        'TWD' => 'TWD - Taiwan Dollar',
        'ZAR' => 'ZAR - South African Rand',
        'BRL' => 'BRL - Brazilian Real',
        'DKK' => 'DKK - Danish Krone',
        'PLN' => 'PLN - Polish Zloty',
        'THB' => 'THB - Thai Baht',
        'MYR' => 'MYR - Malaysian Ringgit',
        'RUB' => 'RUB - Russian Ruble',
        'IDR' => 'IDR - Indonesian Rupiah',
        'TRY' => 'TRY - Turkish Lira',
        'SAR' => 'SAR - Saudi Riyal',
        'AED' => 'AED - UAE Dirham',
        'BDT' => 'BDT - Bangladeshi Taka',
        'PKR' => 'PKR - Pakistani Rupee',
        'EGP' => 'EGP - Egyptian Pound',
        'NGN' => 'NGN - Nigerian Naira',
        'PHP' => 'PHP - Philippine Peso',
        'VND' => 'VND - Vietnamese Dong',
        'KES' => 'KES - Kenyan Shilling',
        'ARS' => 'ARS - Argentine Peso',
        'CLP' => 'CLP - Chilean Peso',
        'COP' => 'COP - Colombian Peso',
        'PEN' => 'PEN - Peruvian Sol',
        'UAH' => 'UAH - Ukrainian Hryvnia',
        'CZK' => 'CZK - Czech Koruna',
        'ILS' => 'ILS - Israeli Shekel',
        'QAR' => 'QAR - Qatari Riyal',
        'KWD' => 'KWD - Kuwaiti Dinar',
    ],
    'currency_symbols' => [
        'USD' => '$', 'EUR' => '€', 'GBP' => '£', 'JPY' => '¥', 'CNY' => '¥',
        'AUD' => 'A$', 'CAD' => 'C$', 'CHF' => 'CHF', 'HKD' => 'HK$', 'SGD' => 'S$',
        'SEK' => 'kr', 'KRW' => '₩', 'NOK' => 'kr', 'NZD' => 'NZ$', 'INR' => '₹',
        'MXN' => 'MX$', 'TWD' => 'NT$', 'ZAR' => 'R', 'BRL' => 'R$', 'DKK' => 'kr',
        'PLN' => 'zł', 'THB' => '฿', 'MYR' => 'RM', 'RUB' => '₽', 'IDR' => 'Rp',
        'TRY' => '₺', 'SAR' => '﷼', 'AED' => 'د.إ', 'BDT' => '৳', 'PKR' => '₨',
        'EGP' => 'E£', 'NGN' => '₦', 'PHP' => '₱', 'VND' => '₫', 'KES' => 'KSh',
        'ARS' => 'AR$', 'CLP' => 'CL$', 'COP' => 'COL$', 'PEN' => 'S/', 'UAH' => '₴',
        'CZK' => 'Kč', 'ILS' => '₪', 'QAR' => 'ر.ق', 'KWD' => 'د.ك',
    ],

    'timezones' => [
        'Pacific/Midway' => '(UTC-11) Midway Island',
        'Pacific/Honolulu' => '(UTC-10) Hawaii',
        'America/Anchorage' => '(UTC-09) Alaska',
        'America/Los_Angeles' => '(UTC-08) Pacific Time',
        'America/Denver' => '(UTC-07) Mountain Time',
        'America/Chicago' => '(UTC-06) Central Time',
        'America/New_York' => '(UTC-05) Eastern Time',
        'America/Halifax' => '(UTC-04) Atlantic Time',
        'America/Sao_Paulo' => '(UTC-03) Brasilia',
        'Atlantic/South_Georgia' => '(UTC-02) South Georgia',
        'Atlantic/Azores' => '(UTC-01) Azores',
        'Europe/London' => '(UTC+00) London',
        'Europe/Paris' => '(UTC+01) Paris, Berlin',
        'Europe/Helsinki' => '(UTC+02) Helsinki, Cairo',
        'Europe/Moscow' => '(UTC+03) Moscow, Riyadh',
        'Asia/Dubai' => '(UTC+04) Dubai',
        'Asia/Karachi' => '(UTC+05) Karachi',
        'Asia/Dhaka' => '(UTC+06) Dhaka',
        'Asia/Bangkok' => '(UTC+07) Bangkok',
        'Asia/Shanghai' => '(UTC+08) Beijing, Singapore',
        'Asia/Tokyo' => '(UTC+09) Tokyo, Seoul',
        'Australia/Sydney' => '(UTC+10) Sydney',
        'Pacific/Noumea' => '(UTC+11) Solomon Islands',
        'Pacific/Auckland' => '(UTC+12) Auckland',
    ],
];
